In [13]:
import pandas as pd
df = pd.read_csv('london_housing.csv')

In [14]:
df.head()

,date,area,average_price,code,houses_sold,no_of_crimes
0,1/1/1995,city of london,91449,E09000001,17.0,NaN
1,2/1/1995,city of london,82203,E09000001,7.0,NaN
2,3/1/1995,city of london,79121,E09000001,14.0,NaN
3,4/1/1995,city of london,77101,E09000001,7.0,NaN
4,5/1/1995,city of london,84409,E09000001,10.0,NaN

1/What is the overall time range of the dataset (min and max dates)?

In [17]:
df.date = pd.to_datetime(df.date)

In [18]:
df.dtypes

date             datetime64[ns]
area                     object
average_price             int64
code                     object
houses_sold             float64
no_of_crimes            float64
dtype: object

In [19]:
df.date.min()

Timestamp('1995-01-01 00:00:00')

In [21]:
df.date.max()

Timestamp('2020-01-01 00:00:00')

2/Which area has the highest average house price overall?

In [34]:
df.groupby('area')['average_price'].mean().sort_values().tail(1)

area
kensington and chelsea    742060.368771
Name: average_price, dtype: float64

3/Which area has the lowest average house price overall?

In [35]:
df.groupby('area')['average_price'].mean().sort_values().head(1)

area
north east    97041.076412
Name: average_price, dtype: float64

4/ What is the mean, median, and standard deviation of house prices across all areas?

In [33]:
df.average_price.describe().round(2)

count      13549.00
mean      263519.68
std       187617.50
min        40722.00
25%       132380.00
50%       222919.00
75%       336843.00
max      1463378.00
Name: average_price, dtype: float64

5/ How many missing values exist in houses_sold and no_of_crimes?

In [ ]:
df[['houses_sold','no_of_crimes']].isna().sum()

houses_sold       94
no_of_crimes    6110
dtype: int64

6/ Convert date to datetime and extract year. What was the average house price trend by year across London?

In [ ]:
df.groupby('date')['average_price'].mean()
#df.date = df.date.dt.year

date
1995     75880.235185
1996     78875.274908
1997     89618.350000
1998    101747.073801
1999    114256.172222
2000    139979.442593
2001    156932.355556
2002    182190.731481
2003    205099.553704
2004    224604.720370
2005    233314.512963
2006    249303.109259
2007    285944.279630
2008    287478.972222
2009    259296.896296
2010    287559.164815
2011    294819.138889
2012    309409.501852
2013    334589.564815
2014    388208.392593
2015    421356.100000
2016    454884.461111
2017    469978.938889
2018    467240.674074
2019    460056.659259
2020    463329.977778
Name: average_price, dtype: float64

7/ Which year saw the biggest increase in average house prices?

In [54]:
yearly_diff = df.groupby('date')['average_price'].mean().diff()
yearly_diff.idxmax()

np.int32(2014)

8/ Compare the average number of houses sold per year — do you see a decline or growth trend?

In [57]:
df.groupby('date').houses_sold.mean().round()

date
1995    3180.0
1996    3864.0
1997    4389.0
1998    4210.0
1999    4809.0
2000    4473.0
2001    4929.0
2002    5325.0
2003    4915.0
2004    5023.0
2005    4202.0
2006    5261.0
2007    5051.0
2008    2550.0
2009    2459.0
2010    2661.0
2011    2650.0
2012    2698.0
2013    3230.0
2014    3789.0
2015    3747.0
2016    3683.0
2017    3602.0
2018    3415.0
2019    3177.0
2020       NaN
Name: houses_sold, dtype: float64

9/ For the borough "city of london", plot average house prices over time. Does it follow the same trend as the London-wide average?

In [63]:
df.groupby('area').get_group('city of london')[["date", "average_price"]]

     date  average_price
0    1995          91449
1    1995          82203
2    1995          79121
3    1995          77101
4    1995          84409
..    ...            ...
296  2019         792034
297  2019         827093
298  2019         777610
299  2019         734872
300  2020         775309

[301 rows x 2 columns]

10/ Which borough had the highest number of crimes reported in any single year, and what was the corresponding average house price?

In [71]:
df[['area','no_of_crimes','average_price']].sort_values(by = ['average_price','no_of_crimes'],ascending=[False, False]).head()

                        area  no_of_crimes  average_price
6001  kensington and chelsea        1737.0        1463378
6008  kensington and chelsea        2339.0        1418032
5990  kensington and chelsea        1367.0        1412255
5992  kensington and chelsea        1723.0        1399839
5989  kensington and chelsea        1534.0        1394421