In [19]:
import pandas as pd

df = pd.read_csv('/Users/eric5805/Documents/1-YEAR-TRAINING/Projects/Car Sales/data/raw/raw.csv')

In [26]:
df.head(5)

,Manufacturer,Model,Engine size,Fuel type,Year of manufacture,Mileage,Price
0,Ford,Fiesta,1.0,Petrol,2002,127300,3074
1,Porsche,718 Cayman,4.0,Petrol,2016,57850,49704
2,Ford,Mondeo,1.6,Diesel,2014,39190,24072
3,Toyota,RAV4,1.8,Hybrid,1988,210814,1705
4,VW,Polo,1.0,Petrol,2006,127869,4101

In [27]:
df.columns

Index(['Manufacturer', 'Model', 'Engine size', 'Fuel type',
       'Year of manufacture', 'Mileage', 'Price'],
      dtype='object')

In [22]:
df.dtypes # no change

Manufacturer            object
Model                   object
Engine size            float64
Fuel type               object
Year of manufacture      int64
Mileage                  int64
Price                    int64
False                   object
dtype: object

In [23]:
df.isna().sum() # 0

Manufacturer           0
Model                  0
Engine size            0
Fuel type              0
Year of manufacture    0
Mileage                0
Price                  0
False                  0
dtype: int64

In [24]:
df[['Model','Manufacturer']]

            Model Manufacturer
0          Fiesta         Ford
1      718 Cayman      Porsche
2          Mondeo         Ford
3            RAV4       Toyota
4            Polo           VW
...           ...          ...
49995          M5          BMW
49996       Prius       Toyota
49997      Mondeo         Ford
49998       Focus         Ford
49999        Golf           VW

[50000 rows x 2 columns]