In [13]:
import pandas as pd

In [14]:
# Detect encoding
import chardet

with open("superstore_ds.csv", "rb") as f:
    result = chardet.detect(f.read(50000))

In [17]:
df = pd.read_csv("superstore_ds.csv", encoding=result["encoding"])

In [18]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [23]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

1/ How many unique customers are in the dataset?

In [20]:
df['Customer ID'].nunique()

793

2/ Which category has the highest total sales?

In [28]:
df.groupby('Category')['Sales'].sum().idxmax()

'Technology'

3/ What is the average discount applied across all orders?

In [30]:
df.groupby('Order ID')['Discount'].mean()

Order ID
CA-2014-100006    0.000000
CA-2014-100090    0.200000
CA-2014-100293    0.200000
CA-2014-100328    0.200000
CA-2014-100363    0.200000
                    ...
US-2017-168802    0.200000
US-2017-169320    0.000000
US-2017-169488    0.000000
US-2017-169502    0.000000
US-2017-169551    0.283333
Name: Discount, Length: 5009, dtype: float64

4/ Convert Order Date to datetime. What year had the highest total profit?

In [77]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Year'] = df['Order Date'].dt.year

In [81]:
df.groupby('Year')['Profit'].sum().idxmax()

np.int32(2017)

In [76]:
df.groupby('Order Date')['Profit'].idxmax().sort_values(ascending=False).head()

Order Date
2014-01-21    9989
2015-05-17    9985
2015-06-28    9970
2017-12-11    9968
2017-06-01    9948
Name: Profit, dtype: int64

5/ Which month tends to have the most orders?

In [50]:
df['Month'] = df['Order Date'].dt.month
df.groupby('Month')['Order ID'].nunique().sort_values(ascending=False).head(1)

Month
11    753
Name: Order ID, dtype: int64

6/ Which customer has placed the most orders?

In [58]:
df.groupby('Customer ID')['Order ID'].count().sort_values(ascending=False).head(1)

Customer ID
WB-21850    37
Name: Order ID, dtype: int64

7/ Which segment contributes the highest profit margin (profit ÷ sales)?

In [59]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Month'],
      dtype='object')

In [66]:
df['Segment'].value_counts()

Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64

In [74]:
(df.groupby('Segment'))[['Sales','Profit']].sum().assign(Margin =lambda x : x['Profit']/x['Sales']).sort_values(by = 'Margin',ascending=False).head(1)

                   Sales      Profit    Margin
Segment
Home Office  429653.1485  60298.6785  0.140343

8/ Highest sales region

In [82]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Month',
       'Year'],
      dtype='object')

In [87]:
df.groupby('Region')['Sales'].idxmax().sort_values(ascending=False)

Region
West       8153
Central    6826
South      2697
East       2623
Name: Sales, dtype: int64

9/Top 10 products by sales

In [109]:
df.groupby('Product ID')[['Product Name','Sales']].sum().round(2).sort_values(by = 'Sales',ascending=False).head(10)

                                                      Product Name     Sales
Product ID
TEC-CO-10004722  Canon imageCLASS 2200 Advanced CopierCanon ima...  61599.82
OFF-BI-10003527  Fellowes PB500 Electric Punch Plastic Comb Bin...  27453.38
TEC-MA-10002412  Cisco TelePresence System EX90 Videoconferenci...  22638.48
FUR-CH-10002024  HON 5400 Series Task Chairs for Big and TallHO...  21870.58
OFF-BI-10001359  GBC DocuBind TL300 Electric Binding SystemGBC ...  19823.48
OFF-BI-10000545  GBC Ibimaster 500 Manual ProClick Binding Syst...  19024.50
TEC-CO-10001449  Hewlett Packard LaserJet 3310 CopierHewlett Pa...  18839.69
TEC-MA-10001127  HP Designjet T520 Inkjet Large Format Printer ...  18374.90
OFF-BI-10004995  GBC DocuBind P400 Electric Binding SystemGBC D...  17965.07
OFF-SU-10000151  High Speed Automatic Electric Letter OpenerHig...  17030.31

10/ Worst profit sub-category

In [118]:
df.groupby('Sub-Category')[['Sub-Category','Profit']].sum(numeric_only= True).sort_values(by = 'Profit',ascending=True)

                  Profit
Sub-Category
Tables       -17725.4811
Bookcases     -3472.5560
Supplies      -1189.0995
Fasteners       949.5182
Machines       3384.7569
Labels         5546.2540
Art            6527.7870
Envelopes      6964.1767
Furnishings   13059.1436
Appliances    18138.0054
Storage       21278.8264
Chairs        26590.1663
Binders       30221.7633
Paper         34053.5693
Accessories   41936.6357
Phones        44515.7306
Copiers       55617.8249

11/Average sales per order per state

In [119]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Month',
       'Year'],
      dtype='object')

In [131]:
df.groupby('State')[['Sales','Order ID']].agg({'Sales' :'sum','Order ID' : 'nunique'}).assign(avg =lambda x: x['Sales']/x['Order ID']).sort_values(by = 'avg')

                            Sales  Order ID          avg
State
Kansas                  2914.3100        14   208.165000
New Mexico              4783.5220        22   217.432818
South Dakota            1315.5600         5   263.112000
Iowa                    4579.7600        17   269.397647
Illinois               80166.1010       276   290.456888
Connecticut            13384.3570        45   297.430156
Oregon                 17431.1500        56   311.270536
Nebraska                7464.9300        23   324.562174
Arizona                35282.0010       108   326.685194
Ohio                   78258.1360       236   331.602271
Tennessee              30661.8730        91   336.943659
Texas                 170188.0458       487   349.462106
Idaho                   4382.4860        11   398.407818
Pennsylvania          116511.9140       288   404.555257
Colorado               32108.1180        79   406.431873
North Carolina         55603.1640       136   408.846794
Mississippi            10771.3400        26   414.282308
Maine                   1270.5300         3   423.510000
South Carolina          8481.7100        20   424.085500
New Hampshire           7292.5240        17   428.972000
Utah                   11220.0560        26   431.540615
Arkansas               11678.1300        27   432.523333
Louisiana               9217.0300        21   438.906190
Florida                89473.7080       200   447.368540
California            457687.6315      1021   448.273880
North Dakota             919.9100         2   459.955000
Massachusetts          28634.4340        62   461.845710
Maryland               23705.5230        46   515.337457
Georgia                49095.8400        91   539.514725
Washington            138641.2700       256   541.567461
New York              310876.2710       562   553.160625
Alabama                19510.6400        34   573.842353
Oklahoma               19683.3900        34   578.923235
New Jersey             35764.3120        61   586.300197
Kentucky               36591.7500        61   599.864754
West Virginia           1209.8240         2   604.912000
Wisconsin              32114.6100        53   605.936038
Virginia               70636.7200       115   614.232348
Delaware               27451.0690        44   623.887932
Michigan               76269.6140       117   651.877043
Minnesota              29863.1500        44   678.707955
Montana                 5589.3520         8   698.669000
District of Columbia    2865.0200         4   716.255000
Nevada                 16729.1020        23   727.352261
Indiana                53555.3600        73   733.635068
Missouri               22205.1500        30   740.171667
Rhode Island           22627.9560        25   905.118240
Vermont                 8929.3700         6  1488.228333
Wyoming                 1603.1360         1  1603.136000

12/ Top 3 customers in each region by sales

In [148]:
df['Customer ID'].nunique()

793

In [168]:
(df.groupby(['Region','Customer ID'])['Sales'].sum()
                                            .round(2)
                                            .reset_index()
                                            .sort_values(by = ['Region','Sales'], ascending=[True,False])).groupby('Region').head(3)

       Region Customer ID     Sales
588   Central    TC-20980  18437.14
6     Central    AB-10105  12181.59
68    Central    BM-11140  10539.90
1250     East    TA-21385  13723.50
909      East    HL-15040  10522.55
718      East    BS-11365  10022.29
1754    South    SM-20320  23669.20
1744    South    SE-20110   8805.04
1500    South    GT-14635   8167.42
2354     West    RB-19360  14345.28
2193     West    KL-16645   8472.39
2037     West    EH-13765   7447.77